// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Admin.proto

package grpc;

public interface RequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.Request)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string cid = 1;</code>
   */
  java.lang.String getCid();
  /**
   * <code>string cid = 1;</code>
   */
  com.google.protobuf.ByteString
      getCidBytes();

  /**
   * <code>string data = 2;</code>
   */
  java.lang.String getData();
  /**
   * <code>string data = 2;</code>
   */
  com.google.protobuf.ByteString
      getDataBytes();
}
